name: Java CI with Maven
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B clean package
    - name: Create JaCoCo report and submit to Coveralls
      run: mvn -B jacoco:report coveralls:report -DrepoToken=${{ secrets.COVERALLS_REPO_TOKEN }}
    - name: Update checkstyle report
      run: |
        cp target/site/badges/checkstyle-result.svg .github/
        git add .github/checkstyle-result.svg
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
          exit 0
        else
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git commit -m "Runner: update checkstyle [skip ci]"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        fi